$(function(){
		$("#A").mouseover(function(){
			$("#A").css("font-size","70px");
		});
		$("#A").mouseleave(function(){
			$("#A").css("font-size","50px");
		});
		$("#B").mouseover(function(){
			$("#B").css("font-size","70px");
		});
		$("#B").mouseleave(function(){
			$("#B").css("font-size","50px");
		});
		$("#C").mouseover(function(){
			$("#C").css("font-size","70px");
		});
		$("#C").mouseleave(function(){
			$("#C").css("font-size","50px");
		});
		$("#D").mouseover(function(){
			$("#D").css("font-size","70px");
		});
		$("#D").mouseleave(function(){
			$("#D").css("font-size","50px");
		});
		$("#E").mouseover(function(){
			$("#E").css("font-size","70px");
		});
		$("#E").mouseleave(function(){
			$("#E").css("font-size","50px");
		});
		$("#F").mouseover(function(){
			$("#F").css("font-size","70px");
		});
		$("#F").mouseleave(function(){
			$("#F").css("font-size","50px");
		});
		$("#G").mouseover(function(){
			$("#G").css("font-size","70px");
		});
		$("#G").mouseleave(function(){
			$("#G").css("font-size","50px");
		});
		$("#H").mouseover(function(){
			$("#H").css("font-size","70px");
		});
		$("#H").mouseleave(function(){
			$("#H").css("font-size","50px");
		});
		$("#I").mouseover(function(){
			$("#I").css("font-size","70px");
		});
		$("#I").mouseleave(function(){
			$("#I").css("font-size","50px");
		});
		$("#J").mouseover(function(){
			$("#J").css("font-size","70px");
		});
		$("#J").mouseleave(function(){
			$("#J").css("font-size","50px");
		});
		$("#K").mouseover(function(){
			$("#K").css("font-size","70px");
		});
		$("#K").mouseleave(function(){
			$("#K").css("font-size","50px");
		});
		$("#L").mouseover(function(){
			$("#L").css("font-size","70px");
		});
		$("#L").mouseleave(function(){
			$("#L").css("font-size","50px");
		});
		$("#M").mouseover(function(){
			$("#M").css("font-size","70px");
		});
		$("#M").mouseleave(function(){
			$("#M").css("font-size","50px");
		});
		$("#N").mouseover(function(){
			$("#N").css("font-size","70px");
		});
		$("#N").mouseleave(function(){
			$("#N").css("font-size","50px");
		});
		$("#O").mouseover(function(){
			$("#O").css("font-size","70px");
		});
		$("#O").mouseleave(function(){
			$("#O").css("font-size","50px");
		});
		$("#P").mouseover(function(){
			$("#P").css("font-size","70px");
		});
		$("#P").mouseleave(function(){
			$("#P").css("font-size","50px");
		});
		$("#Q").mouseover(function(){
			$("#Q").css("font-size","70px");
		});
		$("#Q").mouseleave(function(){
			$("#Q").css("font-size","50px");
		});
		$("#R").mouseover(function(){
			$("#R").css("font-size","70px");
		});
		$("#R").mouseleave(function(){
			$("#R").css("font-size","50px");
		});
		$("#S").mouseover(function(){
			$("#S").css("font-size","70px");
		});
		$("#S").mouseleave(function(){
			$("#S").css("font-size","50px");
		});
		$("#T").mouseover(function(){
			$("#T").css("font-size","70px");
		});
		$("#T").mouseleave(function(){
			$("#T").css("font-size","50px");
		});
		$("#U").mouseover(function(){
			$("#U").css("font-size","70px");
		});
		$("#U").mouseleave(function(){
			$("#U").css("font-size","50px");
		});
		$("#V").mouseover(function(){
			$("#V").css("font-size","70px");
		});
		$("#V").mouseleave(function(){
			$("#V").css("font-size","50px");
		});
		$("#W").mouseover(function(){
			$("#W").css("font-size","70px");
		});
		$("#W").mouseleave(function(){
			$("#W").css("font-size","50px");
		});
		$("#X").mouseover(function(){
			$("#X").css("font-size","70px");
		});
		$("#X").mouseleave(function(){
			$("#X").css("font-size","50px");
		});
		$("#Y").mouseover(function(){
			$("#Y").css("font-size","70px");
		});
		$("#Y").mouseleave(function(){
			$("#Y").css("font-size","50px");
		});
		$("#Z").mouseover(function(){
			$("#Z").css("font-size","70px");
		});
		$("#Z").mouseleave(function(){
			$("#Z").css("font-size","50px");
		});
		$(".btn").click(function(){
			$(".input").toggleClass("active").focus().val("");
			$(this).toggleClass("animate");
		});

		$("#exit").mouseover(function(){
			$("#exit").css("text-shadow"," 1px 1px 1px #2F4F4F");
		});
		$("#exit").mouseleave(function(){
			$("#exit").css("text-shadow","none");
		});

});